#!/usr/bin/env bash
# Displays Best School 10 times, and on 9th time also prints Hi

count=1

while [ $count -le 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi

  count=$((count + 1))
done
