#!/usr/bin/env bash
# Displays PID and process name of processes containing the word bash
for pid in /proc/[0-9]*
do
    if grep -i bash "$pid/comm" > /dev/null 2>&1
    then
        cmd=$(cat "$pid/comm")
        echo "$pid" | rev | cut -d/ -f1 | rev | xargs -I{} echo "{} $cmd"
    fi
done


